# Generated by Django 4.2.3 on 2023-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_slug_food_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Стол')),
                ('user_book', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Имя клиента')),
            ],
            options={
                'verbose_name': 'Зарезервировать стол',
                'verbose_name_plural': 'Зарезервировать столы',
                'ordering': ['table'],
            },
        ),
    ]
