# Generated by Django 4.2.3 on 2023-08-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booktable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='user_book',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Имя клиента'),
        ),
    ]
