# Generated by Django 4.2.3 on 2023-08-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_booktable_user_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='is_busy',
            field=models.BooleanField(default=True, verbose_name='Занятый стол'),
        ),
    ]
