# Generated by Django 4.2.3 on 2023-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booktable_is_busy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('content', models.TextField(blank=True, verbose_name='Описания')),
            ],
            options={
                'verbose_name': 'Отзивы',
                'verbose_name_plural': 'Отзивы',
                'ordering': ['id'],
            },
        ),
    ]
