# Generated by Django 4.2.3 on 2023-12-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(blank=True, verbose_name='Текст пользователя')),
            ],
        ),
    ]
